"use client"

import { useEffect, useState } from 'react'
import { useAccount } from 'wagmi'
import { ResponsiveContainer, Scatter, ScatterChart, Tooltip, XAxis, YAxis } from 'recharts'
import { ManifestationToast } from '@/components/ManifestationToast'
import { Check, Plus, BookOpen, Footprints, Sparkles } from 'lucide-react'
import { getLocalEntries } from '@/lib/localStorage'
import { getUserProfile } from '@/lib/contract'

interface Habit {
  id: string
  name: string
  icon: string
  streak: number
  completed: boolean
  aiSuggested?: boolean
  reason?: string
}

const WELCOME_HABITS: Habit[] = [
  { id: '1', name: 'No-phone meal', icon: '📵', streak: 0, completed: false },
  { id: '2', name: 'Meditation', icon: '🧘', streak: 0, completed: false },
  { id: '3', name: '30min workout', icon: '💪', streak: 0, completed: false },
]

const NEW_USER_AI_SUGGESTED: Habit[] = [
  { 
    id: 'ai1', 
    name: 'Morning gratitude', 
    icon: '�', 
    streak: 0, 
    completed: false, 
    aiSuggested: true,
    reason: 'Start your day with appreciation — the foundation of wellness'
  },
  { 
    id: 'ai2', 
    name: '5-min breathing', 
    icon: '🌬️', 
    streak: 0, 
    completed: false, 
    aiSuggested: true,
    reason: 'Box breathing reduces cortisol and improves focus'
  },
  { 
    id: 'ai3', 
    name: 'Digital sunset', 
    icon: '🌅', 
    streak: 0, 
    completed: false, 
    aiSuggested: true,
    reason: 'Screen-free evenings lead to deeper, more restorative sleep'
  },
]

const WEEKLY_LETTER_NEW = {
  title: "Welcome to Your Wellness Journey",
  subtitle: "Your first steps toward balance",
  body: `Dear Friend,

Welcome to ZenAgent — your private wellness companion on the blockchain. This is the beginning of something meaningful.

Right now, your journal is empty and your streak is at zero. That's perfect. Every expert was once a beginner, and every streak started with day one.

The most powerful thing you can do today? Complete your first check-in. Track your mood, note your stress level, and write one thing you're grateful for. That's it. Small actions, consistently taken, become transformation.

The market will always be volatile. Your wellbeing doesn't have to be. You are building calm momentum, one breath at a time.

Your ZenAgent`,
}

const WEEKLY_LETTER_TEMPLATE = {
  title: "Your Week in Review",
  subtitle: "Generated by ZenAgent on 0G Compute",
  body: `Dear {username},

This was a meaningful week. Your average mood was {avgMood}/10 and your average stress was {avgStress}/10. You showed up {checkInCount} out of 7 days. That deserves celebration.

Your stress patterns show correlation with market activity. On days you completed breathing exercises, stress was lower on average.

Your manifestation: You are building something that matters — your wellbeing is the foundation everything else is built on.

Day {streak} of your streak. {badgeEmoji}`,
}

export default function InsightsPage() {
  const { address } = useAccount()
  const [habits, setHabits] = useState<Habit[]>(WELCOME_HABITS)
  const [aiSuggested, setAiSuggested] = useState(NEW_USER_AI_SUGGESTED)
  const [savedQuotes, setSavedQuotes] = useState<{quote: string, date: string, mood: number}[]>([])
  const [showToast, setShowToast] = useState(true)
  const [quote] = useState("Your wellness journey is building momentum. Take a breath and appreciate your progress.")
  const [username, setUsername] = useState('')
  const [entries, setEntries] = useState<Array<{mood: number, stress: number, sleep: number, date: string}>>([])
  const [streak, setStreak] = useState(0)
  const [totalCheckIns, setTotalCheckIns] = useState(0)
  const [isNewUser, setIsNewUser] = useState(true)

  useEffect(() => {
    if (typeof window !== 'undefined') {
      const stored = localStorage.getItem('saved_manifestations')
      if (stored) {
        setSavedQuotes(JSON.parse(stored))
      }
      const user = localStorage.getItem('username')
      if (user) setUsername(user)
    }
  }, [])

  useEffect(() => {
    const loadData = async () => {
      if (!address) return
      try {
        const profile = await getUserProfile(address)
        const checkInCount = Number(profile[2])
        const currentStreak = Number(profile[1])
        setTotalCheckIns(checkInCount)
        setStreak(currentStreak)
        setIsNewUser(checkInCount === 0)
      } catch (e) {
        console.error('Failed to load profile:', e)
      }
    }
    loadData()
  }, [address])

  useEffect(() => {
    const localEntries = getLocalEntries()
    setEntries(localEntries)
    setIsNewUser(localEntries.length === 0 && totalCheckIns === 0)
  }, [totalCheckIns])

  const avgMood = entries.length > 0 ? (entries.reduce((sum, e) => sum + e.mood, 0) / entries.length).toFixed(1) : '0'
  const avgStress = entries.length > 0 ? (entries.reduce((sum, e) => sum + e.stress, 0) / entries.length).toFixed(1) : '0'
  const badgeEmoji = streak >= 90 ? '🌳' : streak >= 30 ? '🌿' : streak >= 7 ? '🌱' : '✨'

  const getWeeklyLetter = () => {
    if (isNewUser) return WEEKLY_LETTER_NEW
    return {
      title: WEEKLY_LETTER_TEMPLATE.title,
      subtitle: WEEKLY_LETTER_TEMPLATE.subtitle,
      body: WEEKLY_LETTER_TEMPLATE.body
        .replace('{username}', username || 'Friend')
        .replace('{avgMood}', avgMood)
        .replace('{avgStress}', avgStress)
        .replace('{checkInCount}', String(entries.length))
        .replace('{streak}', String(streak))
        .replace('{badgeEmoji}', badgeEmoji)
    }
  }

  const weeklyLetter = getWeeklyLetter()
  const chartData = entries.map(e => ({ mood: e.mood, stress: e.stress }))

  const toggleHabit = (id: string) => {
    setHabits(h => h.map(habit => 
      habit.id === id 
        ? { ...habit, completed: !habit.completed, streak: habit.completed ? habit.streak - 1 : habit.streak + 1 }
        : habit
    ))
  }

  const addAiHabit = (habit: Habit) => {
    setHabits([...habits, { ...habit, aiSuggested: false }])
  }

  const saveQuote = () => {
    const newQuote = { quote, date: new Date().toLocaleDateString(), mood: 7 }
    const updated = [newQuote, ...savedQuotes].slice(0, 5)
    setSavedQuotes(updated)
    localStorage.setItem('saved_manifestations', JSON.stringify(updated))
    setShowToast(false)
  }

  return (
    <main className="mx-auto w-full max-w-6xl px-6 py-10">
      <div className="grid gap-6 lg:grid-cols-3">
        {/* Weekly AI Letter */}
        <div className={`rounded-2xl border p-6 backdrop-blur-sm lg:col-span-2 ${isNewUser ? 'border-[#c4b5fd]/20 bg-[#1a1625]' : 'border-[#fbbf24]/20 bg-[#1a1625]'}`}>
          <div className="flex items-center justify-between">
            <div>
              <h2 className={`font-serif text-lg font-semibold ${isNewUser ? 'text-[#c4b5fd]' : 'text-[#fbbf24]'}`}>{weeklyLetter.title}</h2>
              <p className="text-xs text-white/60">{weeklyLetter.subtitle}</p>
            </div>
            {isNewUser ? <Sparkles className="h-5 w-5 text-[#c4b5fd]/60" /> : <BookOpen className="h-5 w-5 text-[#fbbf24]/60" />}
          </div>
          <div className="mt-4 whitespace-pre-wrap font-serif text-sm leading-relaxed text-white/80">
            {weeklyLetter.body}
          </div>
          <div className="mt-4 flex items-center justify-between">
            <span className="text-xs text-white/40">Powered by 0G Compute</span>
            <div className={`flex items-center gap-1 text-xs ${isNewUser ? 'text-[#c4b5fd]' : 'text-[#fbbf24]'}`}>
              <Footprints className="h-3 w-3" />
              {isNewUser ? 'Day 1 — Your journey begins' : `Day ${streak} of your streak`}
            </div>
          </div>
        </div>

        {/* Habit Tracker */}
        <div className="rounded-2xl border border-white/10 bg-white/5 p-6 backdrop-blur-sm">
          <div className="text-sm font-medium text-white">Habit tracker</div>
          <div className="mt-4 grid gap-3">
            {habits.map((habit) => (
              <div
                key={habit.id}
                onClick={() => toggleHabit(habit.id)}
                className={`flex items-center justify-between rounded-xl border p-3 cursor-pointer transition-all ${
                  habit.completed
                    ? 'border-[#22c55e]/30 bg-[#22c55e]/10'
                    : 'border-white/10 bg-white/5 hover:bg-white/10'
                }`}
              >
                <div className="flex items-center gap-2">
                  <span className="text-xl">{habit.icon}</span>
                  <div>
                    <div className="text-sm font-medium text-white">{habit.name}</div>
                    <div className="text-xs text-white/60">{habit.streak} day streak</div>
                  </div>
                </div>
                <div className={`flex h-5 w-5 items-center justify-center rounded-full border ${habit.completed ? 'border-[#22c55e] bg-[#22c55e]' : 'border-white/30'}`}>
                  {habit.completed && <Check className="h-3 w-3 text-[#0f172a]" />}
                </div>
              </div>
            ))}
          </div>

          {/* AI Suggested Habits */}
          <div className="mt-6">
            <div className="text-xs font-medium text-[#c4b5fd]">AI Suggested Habits</div>
            <div className="mt-2 grid gap-2">
              {aiSuggested.map((habit: Habit) => (
                <div key={habit.id} className="rounded-xl border border-[#c4b5fd]/20 bg-[#c4b5fd]/5 p-2">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2">
                      <span className="text-lg">{habit.icon}</span>
                      <div>
                        <div className="text-sm font-medium text-white">{habit.name}</div>
                        <div className="text-xs text-white/50 max-w-[180px]">{habit.reason}</div>
                      </div>
                    </div>
                    <button
                      onClick={() => addAiHabit(habit)}
                      className="flex items-center gap-1 rounded-lg bg-[#c4b5fd]/20 px-2 py-1 text-xs text-[#c4b5fd] hover:bg-[#c4b5fd]/30"
                    >
                      <Plus className="h-3 w-3" />
                      Add
                    </button>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Mood vs Stress Chart */}
        <div className="rounded-2xl border border-white/10 bg-white/5 p-6 backdrop-blur-sm lg:col-span-2">
          <div className="text-sm font-medium text-white">Mood vs Stress</div>
          <div className="mt-4 h-[260px]">
            <ResponsiveContainer width="100%" height="100%">
              <ScatterChart>
                <XAxis dataKey="mood" type="number" domain={[1, 10]} stroke="rgba(255,255,255,0.35)" />
                <YAxis dataKey="stress" type="number" domain={[1, 10]} stroke="rgba(255,255,255,0.35)" />
                <Tooltip contentStyle={{ background: 'rgba(15,23,42,0.95)', border: '1px solid rgba(255,255,255,0.1)' }} />
                <Scatter data={chartData} fill="#c4b5fd" />
              </ScatterChart>
            </ResponsiveContainer>
          </div>
          {chartData.length === 0 && (
            <div className="mt-4 text-xs text-white/50 text-center">
              Complete check-ins with mood and stress data to see your patterns here
            </div>
          )}
        </div>

        {/* Manifestation Feed */}
        <div className="rounded-2xl border border-white/10 bg-white/5 p-6 backdrop-blur-sm">
          <div className="text-sm font-medium text-white">Manifestation feed</div>
          <div className="mt-4 grid gap-2 text-sm text-white/75">
            {(savedQuotes.length > 0 ? savedQuotes : [
              { quote: "I move with calm confidence.", date: '', mood: 0 },
              { quote: "My habits are my identity.", date: '', mood: 0 },
              { quote: "Small actions become big change.", date: '', mood: 0 },
              { quote: "I am consistent and kind to myself.", date: '', mood: 0 },
              { quote: "Today is a clean slate.", date: '', mood: 0 },
            ]).map((item, i) => (
              <div key={i} className="rounded-xl border border-white/10 bg-white/5 p-3">
                <p className="italic">"{item.quote}"</p>
                {item.date && (
                  <div className="mt-1 text-xs text-white/40">
                    {item.date} • Mood {item.mood}/10
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Manifestation Toast */}
      {showToast && (
        <ManifestationToast
          quote={quote}
          onDismiss={() => setShowToast(false)}
          onSave={saveQuote}
        />
      )}
    </main>
  )
}
