"use client"

import { useEffect, useState } from 'react'
import { ResponsiveContainer, Scatter, ScatterChart, Tooltip, XAxis, YAxis } from 'recharts'
import { ManifestationToast } from '@/components/ManifestationToast'
import { Check, Plus, BookOpen, Footprints } from 'lucide-react'

interface Habit {
  id: string
  name: string
  icon: string
  streak: number
  completed: boolean
  aiSuggested?: boolean
  reason?: string
}

const DEFAULT_HABITS: Habit[] = [
  { id: '1', name: 'Morning meditation', icon: '🧘', streak: 12, completed: false },
  { id: '2', name: 'No charts before 9am', icon: '📵', streak: 5, completed: true },
  { id: '3', name: '8+ hours sleep', icon: '😴', streak: 8, completed: false },
]

const AI_SUGGESTED_HABITS: Habit[] = [
  { 
    id: 'ai1', 
    name: 'Evening journal', 
    icon: '📓', 
    streak: 0, 
    completed: false, 
    aiSuggested: true,
    reason: 'Based on your stress patterns, journaling at 9pm could improve sleep by 23%'
  },
  { 
    id: 'ai2', 
    name: 'Pre-market walk', 
    icon: '🚶', 
    streak: 0, 
    completed: false, 
    aiSuggested: true,
    reason: 'Users with your profile report 40% lower trading anxiety after morning exercise'
  },
  { 
    id: 'ai3', 
    name: 'Weekend detox', 
    icon: '📴', 
    streak: 0, 
    completed: false, 
    aiSuggested: true,
    reason: 'Your mood drops 2 points on weekends — a 24h crypto break could help'
  },
]

const WEEKLY_LETTER = {
  title: "Your Week in Review — April 2026",
  subtitle: "Generated by ZenAgent on 0G Compute",
  body: `Dear {username},

This was a meaningful week. Your average mood was 6.8/10 — up from last week's 6.2. You showed up 5 out of 7 days. That deserves celebration.

Your stress spiked Tuesday during market volatility. Your data shows consistent correlation between red market days and lower sleep. On days you completed breathing exercises, stress was 1.8 points lower on average.

Your manifestation: You are building something that matters — your wellbeing is the foundation everything else is built on. The market will do what it does. You choose how you show up.

Day 12 of your streak. 🌿`,
}

const points = [
  { mood: 6, stress: 7 },
  { mood: 7, stress: 6 },
  { mood: 5, stress: 8 },
  { mood: 8, stress: 4 },
  { mood: 7, stress: 5 },
]

export default function InsightsPage() {
  const [habits, setHabits] = useState<Habit[]>(DEFAULT_HABITS)
  const [savedQuotes, setSavedQuotes] = useState<{quote: string, date: string, mood: number}[]>([])
  const [showToast, setShowToast] = useState(true)
  const [quote] = useState("Your wellness journey is building momentum. Take a breath and appreciate your progress.")
  const [username, setUsername] = useState('zenagent')

  useEffect(() => {
    if (typeof window !== 'undefined') {
      const stored = localStorage.getItem('saved_manifestations')
      if (stored) {
        setSavedQuotes(JSON.parse(stored))
      }
      const user = localStorage.getItem('username')
      if (user) setUsername(user)
    }
  }, [])

  const toggleHabit = (id: string) => {
    setHabits(h => h.map(habit => 
      habit.id === id 
        ? { ...habit, completed: !habit.completed, streak: habit.completed ? habit.streak - 1 : habit.streak + 1 }
        : habit
    ))
  }

  const addAiHabit = (habit: Habit) => {
    setHabits([...habits, { ...habit, aiSuggested: false }])
  }

  const saveQuote = () => {
    const newQuote = { quote, date: new Date().toLocaleDateString(), mood: 7 }
    const updated = [newQuote, ...savedQuotes].slice(0, 5)
    setSavedQuotes(updated)
    localStorage.setItem('saved_manifestations', JSON.stringify(updated))
    setShowToast(false)
  }

  return (
    <main className="mx-auto w-full max-w-6xl px-6 py-10">
      <div className="grid gap-6 lg:grid-cols-3">
        {/* Weekly AI Letter */}
        <div className="rounded-2xl border border-[#fbbf24]/20 bg-[#1a1625] p-6 backdrop-blur-sm lg:col-span-2">
          <div className="flex items-center justify-between">
            <div>
              <h2 className="font-serif text-lg font-semibold text-[#fbbf24]">{WEEKLY_LETTER.title}</h2>
              <p className="text-xs text-white/60">{WEEKLY_LETTER.subtitle}</p>
            </div>
            <BookOpen className="h-5 w-5 text-[#fbbf24]/60" />
          </div>
          <div className="mt-4 whitespace-pre-wrap font-serif text-sm leading-relaxed text-white/80">
            {WEEKLY_LETTER.body.replace('{username}', username)}
          </div>
          <div className="mt-4 flex items-center justify-between">
            <span className="text-xs text-white/40">Powered by 0G Compute</span>
            <div className="flex items-center gap-1 text-xs text-[#fbbf24]">
              <Footprints className="h-3 w-3" />
              Day 12 of your streak
            </div>
          </div>
        </div>

        {/* Habit Tracker */}
        <div className="rounded-2xl border border-white/10 bg-white/5 p-6 backdrop-blur-sm">
          <div className="text-sm font-medium text-white">Habit tracker</div>
          <div className="mt-4 grid gap-3">
            {habits.map((habit) => (
              <div
                key={habit.id}
                onClick={() => toggleHabit(habit.id)}
                className={`flex items-center justify-between rounded-xl border p-3 cursor-pointer transition-all ${
                  habit.completed
                    ? 'border-[#22c55e]/30 bg-[#22c55e]/10'
                    : 'border-white/10 bg-white/5 hover:bg-white/10'
                }`}
              >
                <div className="flex items-center gap-2">
                  <span className="text-xl">{habit.icon}</span>
                  <div>
                    <div className="text-sm font-medium text-white">{habit.name}</div>
                    <div className="text-xs text-white/60">{habit.streak} day streak</div>
                  </div>
                </div>
                <div className={`flex h-5 w-5 items-center justify-center rounded-full border ${habit.completed ? 'border-[#22c55e] bg-[#22c55e]' : 'border-white/30'}`}>
                  {habit.completed && <Check className="h-3 w-3 text-[#0f172a]" />}
                </div>
              </div>
            ))}
          </div>

          {/* AI Suggested Habits */}
          <div className="mt-6">
            <div className="text-xs font-medium text-[#c4b5fd]">AI Suggested Habits</div>
            <div className="mt-2 grid gap-2">
              {AI_SUGGESTED_HABITS.map((habit) => (
                <div key={habit.id} className="rounded-xl border border-[#c4b5fd]/20 bg-[#c4b5fd]/5 p-2">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2">
                      <span className="text-lg">{habit.icon}</span>
                      <div>
                        <div className="text-sm font-medium text-white">{habit.name}</div>
                        <div className="text-xs text-white/50 max-w-[180px]">{habit.reason}</div>
                      </div>
                    </div>
                    <button
                      onClick={() => addAiHabit(habit)}
                      className="flex items-center gap-1 rounded-lg bg-[#c4b5fd]/20 px-2 py-1 text-xs text-[#c4b5fd] hover:bg-[#c4b5fd]/30"
                    >
                      <Plus className="h-3 w-3" />
                      Add
                    </button>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Mood vs Stress Chart */}
        <div className="rounded-2xl border border-white/10 bg-white/5 p-6 backdrop-blur-sm lg:col-span-2">
          <div className="text-sm font-medium text-white">Mood vs Stress</div>
          <div className="mt-4 h-[260px]">
            <ResponsiveContainer width="100%" height="100%">
              <ScatterChart>
                <XAxis dataKey="mood" type="number" domain={[1, 10]} stroke="rgba(255,255,255,0.35)" />
                <YAxis dataKey="stress" type="number" domain={[1, 10]} stroke="rgba(255,255,255,0.35)" />
                <Tooltip contentStyle={{ background: 'rgba(15,23,42,0.95)', border: '1px solid rgba(255,255,255,0.1)' }} />
                <Scatter data={points} fill="#c4b5fd" />
              </ScatterChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* Manifestation Feed */}
        <div className="rounded-2xl border border-white/10 bg-white/5 p-6 backdrop-blur-sm">
          <div className="text-sm font-medium text-white">Manifestation feed</div>
          <div className="mt-4 grid gap-2 text-sm text-white/75">
            {(savedQuotes.length > 0 ? savedQuotes : [
              { quote: "I move with calm confidence.", date: '', mood: 0 },
              { quote: "My habits are my identity.", date: '', mood: 0 },
              { quote: "Small actions become big change.", date: '', mood: 0 },
              { quote: "I am consistent and kind to myself.", date: '', mood: 0 },
              { quote: "Today is a clean slate.", date: '', mood: 0 },
            ]).map((item, i) => (
              <div key={i} className="rounded-xl border border-white/10 bg-white/5 p-3">
                <p className="italic">"{item.quote}"</p>
                {item.date && (
                  <div className="mt-1 text-xs text-white/40">
                    {item.date} • Mood {item.mood}/10
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Manifestation Toast */}
      {showToast && (
        <ManifestationToast
          quote={quote}
          onDismiss={() => setShowToast(false)}
          onSave={saveQuote}
        />
      )}
    </main>
  )
}
